"""Fix match-team relationships

Revision ID: 07b49da9ca7a
Revises: 5c6b2bf377f7
Create Date: 2025-09-18 17:38:13.997286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b49da9ca7a'
down_revision: Union[str, Sequence[str], None] = '5c6b2bf377f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
