"""Fix match-team relationships

Revision ID: 148696e3e6b2
Revises: b2a33ae4c48b
Create Date: 2025-09-18 17:58:28.824187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148696e3e6b2'
down_revision: Union[str, Sequence[str], None] = 'b2a33ae4c48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
