"""Initial revision

Revision ID: d27a61261b96
Revises: 
Create Date: 2025-09-18 15:57:34.067416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27a61261b96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('contacts', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('contacts', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_1', sa.Integer(), nullable=False),
    sa.Column('player_2', sa.Integer(), nullable=False),
    sa.Column('player_3', sa.Integer(), nullable=False),
    sa.Column('player_4', sa.Integer(), nullable=False),
    sa.Column('player_5', sa.Integer(), nullable=False),
    sa.Column('reserve', sa.Integer(), nullable=False),
    sa.Column('trainer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_1'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_2'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_3'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_4'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_5'], ['players.id'], ),
    sa.ForeignKeyConstraint(['reserve'], ['players.id'], ),
    sa.ForeignKeyConstraint(['trainer'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('from_country', sa.String(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_team_id', sa.Integer(), nullable=False),
    sa.Column('second_team_id', sa.Integer(), nullable=False),
    sa.Column('time_match', sa.Date(), nullable=False),
    sa.Column('result_first', sa.Integer(), nullable=False),
    sa.Column('result_second', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['second_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trophies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trophies')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('compounds')
    op.drop_table('trainers')
    op.drop_table('players')
    # ### end Alembic commands ###
